"""TEST-04: hardware-gated end-to-end validation of the `enpipe` CLI
(detect -> encode -> mux) against real media on real Intel Arc QSV
hardware -- the milestone capstone. SDR and synthetic HDR10 sources are
generated in-test and genuinely encoded on this devcontainer's Arc GPU;
HDR10+/genuine Dolby Vision are fixture-gated (D-06) because dynamic
metadata / real RPU content cannot be reliably synthesized in-sandbox.

IMPORTANT (qwen H1): the SOURCE clips generated by `_make_multiscene_clip`
are produced by a SOFTWARE ffmpeg encode (libx264/libx265) -- that step
needs no GPU at all. The `hardware` marker / `_require_hardware` gate below
applies ONLY to the `enpipe` pipeline's own encode step, which drives the
real `qsvencc` QSV hardware encoder against /dev/dri/renderD128.

Every `enpipe encode` invocation in this file MUST pass --no-metrics:
qsvencc's --psnr/--ssim computation requires an OpenCL device that is
unavailable on this Debian-trixie devcontainer (Intel's own OpenCL ICD is
absent -- see scratch/parity_encode.py:81-94, METRICS_UNAVAILABLE). Without
--no-metrics, chunk_command() appends --psnr --ssim and qsvencc fails with
rc=255 deterministically. Metrics *parsing* is already covered by TEST-01's
fast tier (tests/unit/encoding/test_chunk.py) -- it is not this test's job.

DV RPU verification NEVER uses the mutating dovi_rpu ffmpeg bitstream
filter to write, and NEVER uses dovi_tool's RPU-extraction subcommand
(confirmed broken on AV1 input in the installed 2.3.2 version -- see
04-RESEARCH.md). Only a read-only `ffmpeg -h bsf=dovi_rpu` self-check
(AV1-support probe) and read-only `ffprobe -show_entries
frame=side_data_list` inspection are used -- see Task 2's helpers below.

EMPIRICAL CORRECTION vs. the plan's draft interface (recorded here, not
just in the SUMMARY, so a future reader isn't misled by stale assumptions):
HDR10 mastering-display/max-CLL metadata does NOT appear at ffprobe's
STREAM level for this pipeline's mkvmerge-muxed AV1-in-.mkv output --
`ffprobe -show_streams -show_entries stream=side_data_list` returns no
side_data_list key at all (verified directly against a real produced HDR10
.mkv in this session; `mkvinfo` also confirms mkvmerge does not lift
Mastering-display/MaxCLL into a Matroska Colour element for a raw-OBU AV1
track). The metadata DOES survive, but only at the FRAME level
(`frame=side_data_list`), on every single frame -- so test_hdr10 below
checks frame-level side data for HDR10 survival, same probe entry as the
DV RPU check (Task 2) but a different side_data_type string."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Tuple

import pytest

from enpipe.cli.main import main as _enpipe_main
from enpipe.encoding.chunk import count_frames
from enpipe.encoding.hdr import detect_hdr
from enpipe.encoding.keyframes import (
    compute_chunk_seek_trim,
    fmt_seek,
    kf_before,
    keyframe_table,
    keyframe_table_ffprobe,
)
from enpipe.encoding.pipeline import probe_fps
from enpipe.encoding.scenes_io import read_scenes

pytestmark = pytest.mark.hardware

REPO_ROOT = Path(__file__).resolve().parents[2]

_FPS = 24
_SIZE = "320x180"


def _hardware_available() -> bool:
    return Path("/dev/dri/renderD128").exists() and shutil.which("qsvencc") is not None


@pytest.fixture(autouse=True, scope="module")
def _require_hardware():
    if not _hardware_available():
        pytest.skip("no Arc hardware (/dev/dri/renderD128 or qsvencc absent)")


def _run_cli(argv: List[str]) -> None:
    """SystemExit-safe wrapper around enpipe.cli.main.main (opencode L1/L5).

    die() (enpipe.shared.logging) raises SystemExit on any pipeline failure
    -- catching it here and converting to pytest.fail() makes a real
    pipeline failure surface as a clean, readable test failure instead of
    an unhandled SystemExit escaping the test."""
    try:
        _enpipe_main(argv)
    except SystemExit as exc:
        pytest.fail(f"enpipe {argv[0]} failed: {exc}")


def _multiscene_segments(seg_dur: float) -> List[str]:
    """Four alternating color=/smptebars= lavfi segments -- reuses the
    proven multi-cut recipe from
    tests/integration/test_parallel_regression.py's multi_scene_clip
    fixture, so AdaptiveDetector reliably finds real scene cuts (multiple
    chunks -> multiple keyframe-alignment points), just parametrized by
    segment duration so the HDR10 variant can be made short."""
    return [
        f"color=red:duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"smptebars=duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"color=blue:duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"smptebars=duration={seg_dur}:size={_SIZE}:rate={_FPS}",
    ]


def _make_multiscene_clip(dst: Path, *, codec_args: List[str], seg_dur: float) -> None:
    """Generates a multi-cut synthetic clip via a SOFTWARE ffmpeg encode
    (no GPU/hardware gate needed for this step -- see module docstring).
    `codec_args` supplies the pixel-format/color-tag/encoder flags (SDR:
    libx264/yuv420p; HDR10: libx265/yuv420p10le + bt2020/smpte2084 +
    x265-params master-display/max-cll), `seg_dur` controls per-segment
    duration in seconds (kept short for HDR10 to avoid a software-x265
    timeout)."""
    segments = _multiscene_segments(seg_dur)
    inputs: List[str] = []
    for seg in segments:
        inputs += ["-f", "lavfi", "-i", seg]
    filter_complex = (
        "".join(f"[{i}:v]" for i in range(len(segments)))
        + f"concat=n={len(segments)}:v=1[v]"
    )
    cmd = [
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
        *inputs,
        "-filter_complex", filter_complex,
        "-map", "[v]",
        *codec_args,
        str(dst),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


def _verify_frame_counts_and_keyframes(
    src: Path, workdir: Path, scenes_path: Path, final_mkv: Path
) -> None:
    """Independently verifies the two load-bearing correctness invariants
    (RESEARCH Pitfall 4) -- does NOT trust the CLI exit code or the
    pipeline's own internal count_frames()/keyframe_table() calls.

    (a) Per-chunk + total frame counts: re-parses scenes_path independently
        (not reused pipeline state) and, for each chunk_{i:05d}.obu in
        workdir (requires --keep), asserts count_frames(chunk) == (e - s).
        THIS IS THE LOAD-BEARING TRIM-CORRECTNESS INVARIANT -- a wrong
        seek/trim recovers the wrong span, which surfaces here as a
        frame-count mismatch, not as a silent success.

    (b) Non-tautological keyframe alignment (opencode H2): builds an
        INDEPENDENT ground-truth keyframe set via keyframe_table_ffprobe
        (the slow, full-scan path -- NOT keyframe_table, which may take the
        fast EBML path the pipeline itself might also take), then for each
        scene exercises the pipeline's OWN pure compute_chunk_seek_trim
        decision and independently re-derives its chosen seek keyframe via
        kf_before, asserting that keyframe is a REAL member of the
        independent ground-truth set. This replaces the old tautological
        `max({f<=s}) exists` check, which could never fail (frame 0 is
        always a keyframe per keyframe_table_ffprobe's own invariant)."""
    scenes = read_scenes(scenes_path)

    total_expect = 0
    for i, (s, e) in enumerate(scenes):
        chunk = workdir / f"chunk_{i:05d}.obu"
        assert chunk.is_file(), (
            f"missing chunk {chunk} -- did the encode invocation include --keep?"
        )
        expect = e - s
        got = count_frames(chunk)
        assert got == expect, (
            f"chunk {i} ({chunk}): got {got} frames, expected {expect} "
            f"(scene [{s},{e})) -- wrong seek/trim recovered the wrong span"
        )
        total_expect += expect

    final_frames = count_frames(final_mkv)
    assert final_frames == total_expect, (
        f"{final_mkv}: {final_frames} frames total, expected {total_expect} "
        f"(sum of independently re-parsed scene spans)"
    )

    fps = probe_fps(src)
    # INDEPENDENT ground truth: full ffprobe packet scan.
    gt_table = keyframe_table_ffprobe(src, fps)
    gt_kf_frames = {f for f, _ in gt_table}
    # PRODUCTION path: what a real `enpipe encode` actually uses to place chunk
    # seeks -- the hand-rolled EBML/Cues fast-path for .mkv (ffprobe fallback
    # otherwise), i.e. the function ARCHITECTURE.md flags as risking a silent
    # "wrong-but-parseable" keyframe table.
    prod_table = keyframe_table(src, fps)
    prod_kf_frames = {f for f, _ in prod_table}

    # Cross-validate the PRODUCTION keyframe path against the INDEPENDENT ground
    # truth. This is the non-tautological check: a corrupt/wrong Cues parse would
    # yield keyframe frames the ffprobe ground truth does not contain, and fail.
    assert prod_kf_frames == gt_kf_frames, (
        f"production keyframe_table (EBML fast-path) disagrees with the "
        f"independent ffprobe ground truth on {src.name}: "
        f"prod-only={sorted(prod_kf_frames - gt_kf_frames)}, "
        f"gt-only={sorted(gt_kf_frames - prod_kf_frames)}"
    )

    for i, (s, e) in enumerate(scenes):
        # Derive the seek from the PRODUCTION table (what real encode used), then
        # assert the chosen keyframe is a genuine keyframe per the INDEPENDENT
        # ground truth -- catches the production path landing a chunk seek on a
        # non-keyframe (silent frame-shift), not just re-checking a table vs itself.
        seek, _trim = compute_chunk_seek_trim(prod_table, s, e)
        kf_frame, kf_time = kf_before(prod_table, s)
        assert kf_frame in gt_kf_frames, (
            f"scene {i}'s production-derived seek keyframe (frame {kf_frame}) is "
            f"NOT in the independent ground-truth keyframe set -- keyframe "
            f"alignment violated (possible wrong-but-parseable Cues table)"
        )
        assert seek == fmt_seek(kf_time)


def test_sdr(tmp_path: Path) -> None:
    src = tmp_path / "sdr.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )
    assert detect_hdr(src) == [], "sanity: SDR clip must classify with no HDR flags"

    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "sdr.av1.mkv"
    workdir = tmp_path / "sdr.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)


_HDR10_CODEC_ARGS: List[str] = [
    "-pix_fmt", "yuv420p10le",
    "-color_primaries", "bt2020", "-color_trc", "smpte2084", "-colorspace", "bt2020nc",
    "-c:v", "libx265", "-preset", "ultrafast",
    "-x265-params",
    "hdr10=1:hdr10-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:"
    "colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)"
    "WP(15635,16450)L(10000000,1):max-cll=1000,400",
]


def _encoder_available(name: str) -> bool:
    """Word-boundary check of `ffmpeg -encoders` output (opencode M4) --
    symmetric with the hardware-availability gate: the self-hosted Arc
    runner's ffmpeg build may lack libx265, so test_hdr10 must skip cleanly
    rather than fail loud on an environment gap."""
    proc = subprocess.run(["ffmpeg", "-hide_banner", "-encoders"],
                           capture_output=True, text=True)
    return re.search(rf"\b{re.escape(name)}\b", proc.stdout) is not None


def _frame_side_data_types(path: Path) -> List[List[str]]:
    """Per-frame list of side_data_type strings, via read-only ffprobe
    (frame=side_data_list) -- shared by the HDR10 survival check here and
    the DV RPU survival check in Task 2."""
    cmd = ["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_frames",
           "-show_entries", "frame=side_data_list", "-of", "json", str(path)]
    data = json.loads(subprocess.run(cmd, capture_output=True, text=True, check=True).stdout)
    return [
        [sd.get("side_data_type", "") for sd in f.get("side_data_list", [])]
        for f in data.get("frames", [])
    ]


def test_hdr10(tmp_path: Path) -> None:
    if not _encoder_available("libx265"):
        pytest.skip("libx265 encoder not available in this ffmpeg build")

    src = tmp_path / "hdr10.mkv"
    _make_multiscene_clip(src, codec_args=_HDR10_CODEC_ARGS, seg_dur=10)

    assert "--master-display" in detect_hdr(src), (
        "sanity: HDR10 clip must classify with --master-display"
    )

    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "hdr10.av1.mkv"
    workdir = tmp_path / "hdr10.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)

    # HDR10 metadata survival -- FRAME-level (see module docstring's
    # "EMPIRICAL CORRECTION" note): every video frame of the final .mkv
    # must still carry both Mastering-display and Content-light-level side
    # data. Per-frame side data is used here for HDR10 survival ONLY
    # because that is where this pipeline's mkvmerge output actually puts
    # it -- DV RPU (Task 2) also uses frame-level side data, but for a
    # different side_data_type string ("Dolby Vision RPU Data").
    per_frame_types = _frame_side_data_types(out)
    assert per_frame_types, f"no frames read from {out}"
    missing_mastering = sum(
        1 for types in per_frame_types if "Mastering display metadata" not in types
    )
    missing_cll = sum(
        1 for types in per_frame_types if "Content light level metadata" not in types
    )
    assert missing_mastering == 0, (
        f"{missing_mastering}/{len(per_frame_types)} frames of {out} are missing "
        f"Mastering display metadata -- HDR10 survival violated"
    )
    assert missing_cll == 0, (
        f"{missing_cll}/{len(per_frame_types)} frames of {out} are missing "
        f"Content light level metadata -- HDR10 survival violated"
    )


def test_sdr_legacy_oracle_parity(tmp_path: Path) -> None:
    """SC4: legacy/encode_scenes.py remains the executable parity oracle.
    Runs the FROZEN legacy oracle (read-only subprocess, never imported,
    never modified) on the SAME sample + SAME .scenes file the enpipe
    pipeline used, isolating ENCODE parity from detect. Both sides run
    --no-metrics (qsvencc --psnr/--ssim needs an OpenCL device unavailable
    on this devcontainer -- scratch/parity_encode.py:81-94)."""
    src = tmp_path / "sdr_parity.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )
    scenes = src.with_name(src.name + ".scenes")

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    wd_enpipe = tmp_path / "wd_enpipe"
    enpipe_out = tmp_path / "enpipe_out.mkv"
    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(enpipe_out), "--workdir", str(wd_enpipe),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert enpipe_out.is_file()

    wd_legacy = tmp_path / "wd_legacy"
    legacy_out = tmp_path / "legacy_out.mkv"
    legacy_cmd = [
        sys.executable, str(REPO_ROOT / "legacy" / "encode_scenes.py"),
        str(src), str(scenes),
        "-o", str(legacy_out), "--workdir", str(wd_legacy),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ]
    legacy_proc = subprocess.run(
        legacy_cmd, cwd=REPO_ROOT, capture_output=True, text=True
    )
    assert legacy_proc.returncode == 0, (
        f"legacy oracle encode_scenes.py failed (rc={legacy_proc.returncode}): "
        f"{legacy_proc.stderr[-2000:]}"
    )
    assert legacy_out.is_file()

    # PRIMARY GATE: final .mkv frame-count parity.
    assert count_frames(legacy_out) == count_frames(enpipe_out), (
        "enpipe encode frame count does not match the frozen legacy oracle "
        "on the same sample + scenes"
    )

    # Determinism-aware PRE-MUX movie.obu comparison (scratch/parity_encode.py:199-234):
    # byte-identical -> qsvencc is deterministic on this box (STRONG gate holds).
    # differ -> HW AV1 is commonly non-deterministic (EXPECTED case per
    # parity_encode.py) -> fall back to frame-count parity on the pre-mux .obu,
    # which is correct, not a weakening of the check.
    legacy_movie = wd_legacy / "movie.obu"
    enpipe_movie = wd_enpipe / "movie.obu"
    assert legacy_movie.is_file() and enpipe_movie.is_file()
    if legacy_movie.read_bytes() == enpipe_movie.read_bytes():
        pass  # deterministic qsvencc on this box -- byte-identical parity holds
    else:
        assert count_frames(legacy_movie) == count_frames(enpipe_movie), (
            "pre-mux movie.obu differs AND frame counts differ -- qsvencc "
            "non-determinism alone cannot explain this; real parity failure"
        )


# --------------------------------------------------------------------------- #
# D-06/D-07: fixture-gated HDR10+/Dolby-Vision cases. Genuine HDR10+ dynamic
# metadata and genuine DV RPU content cannot be reliably synthesized
# in-sandbox (04-RESEARCH.md "What is confirmed NOT synthesizable") -- these
# tests look for operator-supplied real sample files at FIXTURES_DIR and
# skip cleanly with an explanatory how-to-supply message when absent. A
# pass is NEVER faked: absence of a fixture is not treated as success.
# --------------------------------------------------------------------------- #

FIXTURES_DIR = Path(
    os.environ.get("ENPIPE_TEST_MEDIA", str(REPO_ROOT / "tests" / "fixtures" / "media"))
)


def _fixture(name: str) -> Optional[Path]:
    p = FIXTURES_DIR / name
    return p if p.is_file() else None


def _av1_dovi_self_check() -> bool:
    """Read-only AV1-DOVI-parsing self-check (D-07/Assumption A2, opencode
    L2): confirms the installed ffmpeg's dovi_rpu bitstream filter declares
    AV1 support in its Supported-codecs line via a WORD-BOUNDARY match (not
    a bare substring, which could match spuriously). This is a READ-ONLY
    `-h` (help) invocation -- it does not filter, mutate, or process any
    media; it only inspects what the installed ffmpeg build claims to
    support, so a toolchain downgrade fails loud (skip with an explanation)
    rather than silently under-reporting RPU frames."""
    proc = subprocess.run(["ffmpeg", "-hide_banner", "-h", "bsf=dovi_rpu"],
                           capture_output=True, text=True)
    return re.search(r"\bav1\b", proc.stdout + proc.stderr, re.I) is not None


def _dv_rpu_frame_count(path: Path) -> Tuple[int, int]:
    """Returns (frames_with_rpu, total_frames) via the SAME read-only
    frame-level ffprobe probe as the HDR10 survival check
    (_frame_side_data_types) -- no bitstream filter, no mutation. Counts
    frames whose side_data_list contains a "Dolby Vision RPU Data" entry."""
    per_frame_types = _frame_side_data_types(path)
    with_rpu = sum(1 for types in per_frame_types if "Dolby Vision RPU Data" in types)
    return with_rpu, len(per_frame_types)


def test_hdr10plus(tmp_path: Path) -> None:
    fixture = _fixture("hdr10plus.mkv")
    if fixture is None:
        pytest.skip(
            f"no HDR10+ fixture at {FIXTURES_DIR / 'hdr10plus.mkv'} (or set "
            f"$ENPIPE_TEST_MEDIA to a directory containing hdr10plus.mkv) -- "
            f"see tests/fixtures/media/README.md for how to supply one. This "
            f"is NOT a failure: genuine HDR10+ dynamic-metadata source "
            f"material cannot be synthesized (D-06) and must be operator-"
            f"supplied."
        )

    src = tmp_path / fixture.name
    shutil.copyfile(fixture, src)
    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "hdr10plus.av1.mkv"
    workdir = tmp_path / "hdr10plus.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)


def test_run_parity_vs_two_step(tmp_path: Path) -> None:
    """Phase 5 (D-08): `enpipe run` vs the manual two-step (`enpipe detect`
    then `enpipe encode`) on real Arc hardware. Byte-identical parity is
    guaranteed by construction (D-02) -- run_pipeline builds the same
    per-stage Namespaces the manual two-step CLI produces and writes the
    intermediate `.scenes` to the same derived path (D-04) -- this test
    proves it. Mirrors the determinism-aware pre-mux movie.obu pattern of
    test_sdr_legacy_oracle_parity above, but compares run-vs-two-step
    instead of enpipe-vs-legacy-oracle."""
    src = tmp_path / "run_parity.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )

    # --- SINGLE-COMMAND side: `enpipe run` --- #
    run_out = tmp_path / "run_out.mkv"
    wd_run = tmp_path / "wd_run"
    _run_cli([
        "run", str(src), "-o", str(run_out),
        "--workdir", str(wd_run), "--keep", "--no-audio", "--no-metrics",
        "--detect-jobs", "2", "--encode-jobs", "2",
    ])
    assert run_out.is_file(), f"enpipe run did not write {run_out}"
    # same derivation run_detect itself uses (detection/pipeline.py:42)
    run_scenes = Path(str(src) + ".scenes")
    assert run_scenes.is_file(), (
        f"enpipe run did not keep the .scenes intermediate at {run_scenes} (D-04)"
    )

    # --- TWO-STEP side: manual `enpipe detect` + `enpipe encode`, on a
    # fresh copy of src so its derived `.scenes` path does not collide with
    # run_scenes above --- #
    two_step_dir = tmp_path / "two_step"
    two_step_dir.mkdir()
    src2 = two_step_dir / src.name
    shutil.copyfile(src, src2)
    scenes2 = Path(str(src2) + ".scenes")

    two_out = tmp_path / "two_out.mkv"
    wd_two = tmp_path / "wd_two"
    _run_cli(["detect", str(src2), "--jobs", "2"])
    assert scenes2.is_file(), f"enpipe detect did not write {scenes2}"
    _run_cli([
        "encode", str(src2), str(scenes2),
        "-o", str(two_out), "--workdir", str(wd_two),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert two_out.is_file(), f"enpipe encode did not write {two_out}"

    # COLLISION-AVOIDANCE: distinct tmp copies -> distinct derived paths.
    assert run_scenes != scenes2

    # PRIMARY GATE: final .mkv frame-count parity.
    assert count_frames(run_out) == count_frames(two_out), (
        "enpipe run frame count does not match the manual two-step on the "
        "same source"
    )

    # Determinism-aware PRE-MUX movie.obu comparison (mirrors
    # test_sdr_legacy_oracle_parity above): byte-identical -> qsvencc
    # deterministic on this box (STRONG gate holds); differ -> fall back to
    # frame-count parity on the pre-mux .obu (expected HW AV1
    # non-determinism, not a weakening).
    run_movie = wd_run / "movie.obu"
    two_movie = wd_two / "movie.obu"
    assert run_movie.is_file() and two_movie.is_file()
    if run_movie.read_bytes() == two_movie.read_bytes():
        pass  # deterministic qsvencc on this box -- byte-identical parity holds
    else:
        assert count_frames(run_movie) == count_frames(two_movie), (
            "pre-mux movie.obu differs AND frame counts differ -- qsvencc "
            "non-determinism alone cannot explain this; real parity failure"
        )

    # SCENES BYTE-IDENTITY: detect stage is identical by construction
    # (PySceneDetect is deterministic on a fixed input) even though the
    # run-side and two-step-side .scenes live at different paths.
    assert run_scenes.read_bytes() == scenes2.read_bytes(), (
        "run-side .scenes differs from the two-step-side .scenes byte-for-byte"
    )


def test_dv(tmp_path: Path) -> None:
    fixture = _fixture("dv.mkv")
    if fixture is None:
        pytest.skip(
            f"no Dolby Vision fixture at {FIXTURES_DIR / 'dv.mkv'} (or set "
            f"$ENPIPE_TEST_MEDIA to a directory containing dv.mkv) -- see "
            f"tests/fixtures/media/README.md for how to supply one. This is "
            f"NOT a failure: genuine DV RPU source material cannot be "
            f"synthesized (D-06) and must be operator-supplied."
        )
    if not _av1_dovi_self_check():
        pytest.skip(
            "installed ffmpeg's dovi_rpu bitstream filter does not report "
            "AV1 support -- this toolchain cannot verify AV1 DOVI RPU "
            "side-data (see 04-RESEARCH.md 'DV RPU Verification Mechanism' "
            "/ Assumption A2); upgrade ffmpeg to re-enable this check"
        )

    src_with_rpu, src_total = _dv_rpu_frame_count(fixture)
    assert src_with_rpu > 0, (
        f"DV fixture {fixture} carries no per-frame RPU side-data -- not a "
        f"valid DV fixture, or the fixture itself lacks genuine RPU"
    )

    src = tmp_path / fixture.name
    shutil.copyfile(fixture, src)
    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "dv.av1.mkv"
    workdir = tmp_path / "dv.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)

    # SOURCE-parity of the RPU frame count (opencode M1/qwen M3): the
    # genuine survival invariant is that the RPU frame-count SURVIVES the
    # splice/mux, matching the SOURCE fixture's own count -- not merely
    # "== total", which would be too strict if the source itself is
    # partial (e.g. RPU present only on some frames).
    out_with_rpu, out_total = _dv_rpu_frame_count(out)
    assert out_with_rpu == src_with_rpu and out_with_rpu > 0, (
        f"DV RPU frame-count did not survive splice/mux: source had "
        f"{src_with_rpu}/{src_total} RPU frames, final output has "
        f"{out_with_rpu}/{out_total}"
    )

    # ALSO check source-parity at the pre-mux .obu chunk level (RESEARCH
    # Assumption A3 -- mkvmerge's DV-side-data mux path is distinct from
    # HDR10's, so pre-mux and post-mux must both be verified independently).
    scene_list = read_scenes(scenes)
    chunk_with_rpu_total = 0
    for i in range(len(scene_list)):
        chunk = workdir / f"chunk_{i:05d}.obu"
        w, _ = _dv_rpu_frame_count(chunk)
        chunk_with_rpu_total += w
    assert chunk_with_rpu_total == src_with_rpu, (
        f"pre-mux chunk RPU frame total ({chunk_with_rpu_total}) does not "
        f"match source RPU frame count ({src_with_rpu})"
    )
