"""TEST-04: hardware-gated end-to-end validation of the `enpipe` CLI
(detect -> encode -> mux) against real media on real Intel Arc QSV
hardware -- the milestone capstone. SDR and synthetic HDR10 sources are
generated in-test and genuinely encoded on this devcontainer's Arc GPU;
HDR10+/genuine Dolby Vision are fixture-gated (D-06) because dynamic
metadata / real RPU content cannot be reliably synthesized in-sandbox.

IMPORTANT (qwen H1): the SOURCE clips generated by `_make_multiscene_clip`
are produced by a SOFTWARE ffmpeg encode (libx264/libx265) -- that step
needs no GPU at all. The `hardware` marker / `_require_hardware` gate below
applies ONLY to the `enpipe` pipeline's own encode step, which drives the
real `qsvencc` QSV hardware encoder against /dev/dri/renderD128.

Every `enpipe encode` invocation in this file MUST pass --no-metrics:
qsvencc's --psnr/--ssim computation requires an OpenCL device that is
unavailable on this Debian-trixie devcontainer (Intel's own OpenCL ICD is
absent -- see scratch/parity_encode.py:81-94, METRICS_UNAVAILABLE). Without
--no-metrics, chunk_command() appends --psnr --ssim and qsvencc fails with
rc=255 deterministically. Metrics *parsing* is already covered by TEST-01's
fast tier (tests/unit/encoding/test_chunk.py) -- it is not this test's job.

DV RPU verification NEVER uses the mutating dovi_rpu ffmpeg bitstream
filter to write, and NEVER uses `dovi_tool extract-rpu` (broken on AV1 in
2.3.2, confirmed in 04-RESEARCH.md). Only a read-only `ffmpeg -h
bsf=dovi_rpu` self-check (AV1-support probe) and read-only
`ffprobe -show_entries frame=side_data_list` inspection are used -- see
Task 2's helpers below."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import List

import pytest

from enpipe.cli.main import main as _enpipe_main
from enpipe.encoding.chunk import count_frames
from enpipe.encoding.hdr import detect_hdr
from enpipe.encoding.keyframes import (
    compute_chunk_seek_trim,
    fmt_seek,
    kf_before,
    keyframe_table_ffprobe,
)
from enpipe.encoding.pipeline import probe_fps
from enpipe.encoding.scenes_io import read_scenes

pytestmark = pytest.mark.hardware

REPO_ROOT = Path(__file__).resolve().parents[2]

_FPS = 24
_SIZE = "320x180"


def _hardware_available() -> bool:
    return Path("/dev/dri/renderD128").exists() and shutil.which("qsvencc") is not None


@pytest.fixture(autouse=True, scope="module")
def _require_hardware():
    if not _hardware_available():
        pytest.skip("no Arc hardware (/dev/dri/renderD128 or qsvencc absent)")


def _run_cli(argv: List[str]) -> None:
    """SystemExit-safe wrapper around enpipe.cli.main.main (opencode L1/L5).

    die() (enpipe.shared.logging) raises SystemExit on any pipeline failure
    -- catching it here and converting to pytest.fail() makes a real
    pipeline failure surface as a clean, readable test failure instead of
    an unhandled SystemExit escaping the test."""
    try:
        _enpipe_main(argv)
    except SystemExit as exc:
        pytest.fail(f"enpipe {argv[0]} failed: {exc}")


def _multiscene_segments(seg_dur: float) -> List[str]:
    """Four alternating color=/smptebars= lavfi segments -- reuses the
    proven multi-cut recipe from
    tests/integration/test_parallel_regression.py's multi_scene_clip
    fixture, so AdaptiveDetector reliably finds real scene cuts (multiple
    chunks -> multiple keyframe-alignment points), just parametrized by
    segment duration so the HDR10 variant can be made short."""
    return [
        f"color=red:duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"smptebars=duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"color=blue:duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"smptebars=duration={seg_dur}:size={_SIZE}:rate={_FPS}",
    ]


def _make_multiscene_clip(dst: Path, *, codec_args: List[str], seg_dur: float) -> None:
    """Generates a multi-cut synthetic clip via a SOFTWARE ffmpeg encode
    (no GPU/hardware gate needed for this step -- see module docstring).
    `codec_args` supplies the pixel-format/color-tag/encoder flags (SDR:
    libx264/yuv420p; HDR10: libx265/yuv420p10le + bt2020/smpte2084 +
    x265-params master-display/max-cll), `seg_dur` controls per-segment
    duration in seconds (kept short for HDR10 to avoid a software-x265
    timeout)."""
    segments = _multiscene_segments(seg_dur)
    inputs: List[str] = []
    for seg in segments:
        inputs += ["-f", "lavfi", "-i", seg]
    filter_complex = (
        "".join(f"[{i}:v]" for i in range(len(segments)))
        + f"concat=n={len(segments)}:v=1[v]"
    )
    cmd = [
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
        *inputs,
        "-filter_complex", filter_complex,
        "-map", "[v]",
        *codec_args,
        str(dst),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


def _verify_frame_counts_and_keyframes(
    src: Path, workdir: Path, scenes_path: Path, final_mkv: Path
) -> None:
    """Independently verifies the two load-bearing correctness invariants
    (RESEARCH Pitfall 4) -- does NOT trust the CLI exit code or the
    pipeline's own internal count_frames()/keyframe_table() calls.

    (a) Per-chunk + total frame counts: re-parses scenes_path independently
        (not reused pipeline state) and, for each chunk_{i:05d}.obu in
        workdir (requires --keep), asserts count_frames(chunk) == (e - s).
        THIS IS THE LOAD-BEARING TRIM-CORRECTNESS INVARIANT -- a wrong
        seek/trim recovers the wrong span, which surfaces here as a
        frame-count mismatch, not as a silent success.

    (b) Non-tautological keyframe alignment (opencode H2): builds an
        INDEPENDENT ground-truth keyframe set via keyframe_table_ffprobe
        (the slow, full-scan path -- NOT keyframe_table, which may take the
        fast EBML path the pipeline itself might also take), then for each
        scene exercises the pipeline's OWN pure compute_chunk_seek_trim
        decision and independently re-derives its chosen seek keyframe via
        kf_before, asserting that keyframe is a REAL member of the
        independent ground-truth set. This replaces the old tautological
        `max({f<=s}) exists` check, which could never fail (frame 0 is
        always a keyframe per keyframe_table_ffprobe's own invariant)."""
    scenes = read_scenes(scenes_path)

    total_expect = 0
    for i, (s, e) in enumerate(scenes):
        chunk = workdir / f"chunk_{i:05d}.obu"
        assert chunk.is_file(), (
            f"missing chunk {chunk} -- did the encode invocation include --keep?"
        )
        expect = e - s
        got = count_frames(chunk)
        assert got == expect, (
            f"chunk {i} ({chunk}): got {got} frames, expected {expect} "
            f"(scene [{s},{e})) -- wrong seek/trim recovered the wrong span"
        )
        total_expect += expect

    final_frames = count_frames(final_mkv)
    assert final_frames == total_expect, (
        f"{final_mkv}: {final_frames} frames total, expected {total_expect} "
        f"(sum of independently re-parsed scene spans)"
    )

    fps = probe_fps(src)
    gt_table = keyframe_table_ffprobe(src, fps)  # ground-truth, slow path
    gt_kf_frames = {f for f, _ in gt_table}

    for i, (s, e) in enumerate(scenes):
        # Exercise the pipeline's OWN pure seek/trim decision against the
        # independent ground-truth table.
        seek, _trim = compute_chunk_seek_trim(gt_table, s, e)
        kf_frame, kf_time = kf_before(gt_table, s)
        assert kf_frame in gt_kf_frames, (
            f"scene {i}'s derived seek keyframe (frame {kf_frame}) is NOT a "
            f"member of the independent ground-truth keyframe set -- "
            f"keyframe alignment violated"
        )
        # compute_chunk_seek_trim's returned seek string must agree with an
        # independent fmt_seek(kf_time) derivation -- both consume the same
        # ground-truth table, so this cross-checks the pure function against
        # its own building block, not itself.
        assert seek == fmt_seek(kf_time)


def test_sdr(tmp_path: Path) -> None:
    src = tmp_path / "sdr.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )
    assert detect_hdr(src) == [], "sanity: SDR clip must classify with no HDR flags"

    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "sdr.av1.mkv"
    workdir = tmp_path / "sdr.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)
