"""TEST-04: hardware-gated end-to-end validation of the `enpipe` CLI
(detect -> encode -> mux) against real media on real Intel Arc QSV
hardware -- the milestone capstone. SDR and synthetic HDR10 sources are
generated in-test and genuinely encoded on this devcontainer's Arc GPU;
HDR10+/genuine Dolby Vision are fixture-gated (D-06) because dynamic
metadata / real RPU content cannot be reliably synthesized in-sandbox.

IMPORTANT (qwen H1): the SOURCE clips generated by `_make_multiscene_clip`
are produced by a SOFTWARE ffmpeg encode (libx264/libx265) -- that step
needs no GPU at all. The `hardware` marker / `_require_hardware` gate below
applies ONLY to the `enpipe` pipeline's own encode step, which drives the
real `qsvencc` QSV hardware encoder against /dev/dri/renderD128.

The devcontainer runs on Ubuntu 24.04 + the Intel PPA with intel-opencl-icd,
so qsvencc --psnr/--ssim work. test_sdr, test_hdr10 and
test_sdr_legacy_oracle_parity are parametrized over metrics (Phase 8 D-10d).
In the metrics variant the FULL stderr of every qsvencc call is captured by a
wrapper placed on PATH. An attempt is retried (up to METRICS_ATTEMPTS) only
when every failed qsvencc call failed in the metrics subsystem (D-12, known
defect, backlog) and there is no frame-count mismatch. Any other failure is an
immediate test failure. Exhausting the attempts is a failure marked
METRICS_FAILED (the metrics path is NOT verified; this is not a green). The
remaining tests deliberately keep --no-metrics: metrics are not their subject
and the metrics path is covered by the parametrized tests.

Chunk CONTENT check (`_verify_chunk_first_frames`): the first decoded frame of
every kept chunk is compared by PSNR with the SOURCE frame S that starts the
scene (decoded by the ffmpeg next to $ENPIPE_TEST_FFPROBE), plus a negative
control against source frame S+(K_next-K). It catches `qsvencc --seek` landing
one GOP late (fixed in qsvencc r4663, see
.planning/debug/HANDOFF-qsvencc-seek-firstpkt.md); that failure mode keeps frame
counts and rc intact. Open-GOP sources (leading pictures after a seek keyframe)
are not run through this check: enpipe refuses them up front because qsvencc
shifts --trim by -N on them (see
.planning/debug/HANDOFF-qsvencc-opengop-trim-offset.md);
test_open_gop_source_refused covers the refusal and
test_chunk_content_closed_gop the content check on the same layout with
open-gop=0.

DV RPU verification NEVER uses the mutating dovi_rpu ffmpeg bitstream
filter to write, and NEVER uses dovi_tool's RPU-extraction subcommand
(confirmed broken on AV1 input in the installed 2.3.2 version -- see
04-RESEARCH.md). Only a read-only `ffmpeg -h bsf=dovi_rpu` self-check
(AV1-support probe) and read-only ffprobe inspection are used: per-frame
`-show_entries frame=side_data_list` counted by "Dolby Vision Metadata", and
`-show_streams` for the "DOVI configuration record". The probing binary is
$ENPIPE_TEST_FFPROBE (default "ffprobe"); the pipeline under test always
uses the ffmpeg/ffprobe on PATH -- see the DV helpers below.

EMPIRICAL CORRECTION vs. the plan's draft interface (recorded here, not
just in the SUMMARY, so a future reader isn't misled by stale assumptions):
HDR10 mastering-display/max-CLL metadata does NOT appear at ffprobe's
STREAM level for this pipeline's mkvmerge-muxed AV1-in-.mkv output --
`ffprobe -show_streams -show_entries stream=side_data_list` returns no
side_data_list key at all (verified directly against a real produced HDR10
.mkv in this session; `mkvinfo` also confirms mkvmerge does not lift
Mastering-display/MaxCLL into a Matroska Colour element for a raw-OBU AV1
track). The metadata DOES survive, but only at the FRAME level
(`frame=side_data_list`), on every single frame -- so test_hdr10 below
checks frame-level side data for HDR10 survival, same probe entry as the
DV RPU check (Task 2) but a different side_data_type string."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _chunk_content as content  # noqa: E402
import _concurrency_harness as harness  # noqa: E402

from enpipe.cli.main import main as _enpipe_main
from enpipe.encoding.chunk import count_frames
from enpipe.encoding.hdr import detect_hdr
from enpipe.encoding.keyframes import (
    compute_chunk_seek_trim,
    fmt_seek,
    kf_before,
    keyframe_table,
    keyframe_table_ffprobe,
    probe_leading_frames,
)
from enpipe.encoding.pipeline import probe_fps
from enpipe.encoding.scenes_io import read_scenes
from enpipe.shared.qsvencc_version import QSVENCC_METRICS_MIN_REV

pytestmark = pytest.mark.hardware


REPO_ROOT = Path(__file__).resolve().parents[2]

# ffprobe used ONLY for read-only verification probes. The pipeline under test
# deliberately keeps using the system ffmpeg/ffprobe from PATH. AV1 Dolby
# Vision probing needs ffmpeg >= 7 (e.g. a BtbN static build,
# /opt/ffmpeg-9/bin/ffprobe).
VERIFY_FFPROBE = os.environ.get("ENPIPE_TEST_FFPROBE", "ffprobe")

_FPS = 24
_SIZE = "320x180"


def _hardware_available() -> bool:
    return Path("/dev/dri/renderD128").exists() and shutil.which("qsvencc") is not None


@pytest.fixture(autouse=True, scope="module")
def _require_hardware():
    if not _hardware_available():
        pytest.skip("no Arc hardware (/dev/dri/renderD128 or qsvencc absent)")


def _run_cli(argv: List[str]) -> None:
    """SystemExit-safe wrapper around enpipe.cli.main.main (opencode L1/L5).

    die() (enpipe.shared.logging) raises SystemExit on any pipeline failure
    -- catching it here and converting to pytest.fail() makes a real
    pipeline failure surface as a clean, readable test failure instead of
    an unhandled SystemExit escaping the test."""
    try:
        _enpipe_main(argv)
    except SystemExit as exc:
        pytest.fail(f"enpipe {argv[0]} failed: {exc}")


# --------------------------------------------------------------------------- #
# Metrics variant: full-stderr tap + strict retry rule (D-10d / D-12)
# --------------------------------------------------------------------------- #

# 4 chunks x `--jobs 2`; the measured per-chunk metrics failure rate is
# 1/9..6/15, so 3 attempts per run may not be enough. 5 matches D-13.
METRICS_ATTEMPTS = 5


@pytest.fixture
def metrics_tap(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    # WR-05: каждый вариант с метриками проходит через эту фикстуру, поэтому
    # порог ревизии для пути с метриками (r4658, #319/#320) проверяется здесь.
    # Старая сборка - провал, а не skip.
    rev = harness.qsvencc_revision()
    if rev is None or rev < QSVENCC_METRICS_MIN_REV:
        pytest.fail(
            f"qsvencc ({harness.qsvencc_version_line()!r}) слишком старый для "
            f"пути с метриками: требуется r{QSVENCC_METRICS_MIN_REV} или новее (#319/#320)"
        )
    log_dir = tmp_path / "qsvencc_tap_logs"
    bin_dir = tmp_path / "qsvencc_tap_bin"
    harness.install_qsvencc_tap(bin_dir, log_dir)
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    return log_dir


def _reset_tap(log_dir: Path) -> None:
    for f in log_dir.glob("*"):
        f.unlink()


def _cleanup(paths: List[Path]) -> None:
    for pth in paths:
        if pth.is_dir():
            shutil.rmtree(pth, ignore_errors=True)
        else:
            pth.unlink(missing_ok=True)
            Path(str(pth) + ".metrics.csv").unlink(missing_ok=True)


def _run_cli_metrics_retry(
    argv: List[str], cleanup: List[Path], log_dir: Path,
    attempts: int = METRICS_ATTEMPTS,
) -> int:
    """Run enpipe in-process; retry ONLY on a pure metrics-subsystem failure
    judged by the full tapped stderr (not the 500-char tail inside die())."""
    last: object = None
    for n in range(1, attempts + 1):
        _reset_tap(log_dir)
        try:
            _enpipe_main(argv)
            return n
        except SystemExit as exc:
            last = exc
            fails = harness.tap_failures(log_dir)
            if not harness.metrics_only_failure(fails, str(exc)):
                pytest.fail(
                    f"enpipe {argv[0]} failed (not a metrics-only failure): {exc}; "
                    f"qsvencc failures: {[f[-300:] for f in fails]}"
                )
            _cleanup(cleanup)
    pytest.fail(
        f"METRICS_FAILED x{attempts}: known qsvencc metrics defect (Phase 8 D-12); "
        f"metrics path NOT verified: {last}"
    )


def _run_legacy_metrics_retry(
    cmd: List[str], cleanup: List[Path], log_dir: Path,
    attempts: int = METRICS_ATTEMPTS,
) -> Tuple["subprocess.CompletedProcess[str]", int]:
    """Same rule for the frozen legacy subprocess; only this side is retried."""
    proc = None
    for n in range(1, attempts + 1):
        _reset_tap(log_dir)
        proc = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
        if proc.returncode == 0:
            return proc, n
        fails = harness.tap_failures(log_dir)
        if not harness.metrics_only_failure(fails, proc.stderr):
            pytest.fail(
                f"legacy oracle failed (not a metrics-only failure, rc={proc.returncode}): "
                f"{proc.stderr[-1500:]}; qsvencc failures: {[f[-300:] for f in fails]}"
            )
        _cleanup(cleanup)
    pytest.fail(
        f"METRICS_FAILED x{attempts} (legacy): known qsvencc metrics defect "
        f"(Phase 8 D-12); metrics path NOT verified: {proc.stderr[-500:] if proc else ''}"
    )


def _assert_metrics_csv(out: Path) -> None:
    """<out>.metrics.csv exists with an ИТОГО row with non-empty, parseable
    ssim_all and psnr_avg. `inf` is legitimate (flat scenes / lossless planes);
    `nan` in ИТОГО is an error. Values are not otherwise compared (D-12)."""
    import csv
    import math

    csv_path = Path(str(out) + ".metrics.csv")
    assert csv_path.is_file(), f"metrics CSV missing: {csv_path}"
    with csv_path.open(newline="") as f:
        rows = [r for r in csv.DictReader(f) if r.get("scene") == "ИТОГО"]
    assert rows, f"no ИТОГО row in {csv_path}"
    assert rows[0].get("ssim_all") not in (None, "", "None"), "empty ssim_all"
    assert rows[0].get("psnr_avg") not in (None, "", "None"), "empty psnr_avg"
    for key in ("ssim_all", "psnr_avg"):
        assert not math.isnan(float(rows[0][key])), f"nan {key} in ИТОГО"


def _multiscene_segments(seg_dur: float) -> List[str]:
    """Four alternating color=/smptebars= lavfi segments -- reuses the
    proven multi-cut recipe from
    tests/integration/test_parallel_regression.py's multi_scene_clip
    fixture, so AdaptiveDetector reliably finds real scene cuts (multiple
    chunks -> multiple keyframe-alignment points), just parametrized by
    segment duration so the HDR10 variant can be made short."""
    return [
        f"color=red:duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"smptebars=duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"color=blue:duration={seg_dur}:size={_SIZE}:rate={_FPS}",
        f"smptebars=duration={seg_dur}:size={_SIZE}:rate={_FPS}",
    ]


def _make_multiscene_clip(dst: Path, *, codec_args: List[str], seg_dur: float) -> None:
    """Generates a multi-cut synthetic clip via a SOFTWARE ffmpeg encode
    (no GPU/hardware gate needed for this step -- see module docstring).
    `codec_args` supplies the pixel-format/color-tag/encoder flags (SDR:
    libx264/yuv420p; HDR10: libx265/yuv420p10le + bt2020/smpte2084 +
    x265-params master-display/max-cll), `seg_dur` controls per-segment
    duration in seconds (kept short for HDR10 to avoid a software-x265
    timeout)."""
    segments = _multiscene_segments(seg_dur)
    inputs: List[str] = []
    for seg in segments:
        inputs += ["-f", "lavfi", "-i", seg]
    filter_complex = (
        "".join(f"[{i}:v]" for i in range(len(segments)))
        + f"concat=n={len(segments)}:v=1[v]"
    )
    cmd = [
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
        *inputs,
        "-filter_complex", filter_complex,
        "-map", "[v]",
        *codec_args,
        str(dst),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


def _verify_frame_counts_and_keyframes(
    src: Path, workdir: Path, scenes_path: Path, final_mkv: Path
) -> None:
    """Independently verifies the two load-bearing correctness invariants
    (RESEARCH Pitfall 4) -- does NOT trust the CLI exit code or the
    pipeline's own internal count_frames()/keyframe_table() calls.

    (a) Per-chunk + total frame counts: re-parses scenes_path independently
        (not reused pipeline state) and, for each chunk_{i:05d}.obu in
        workdir (requires --keep), asserts count_frames(chunk) == (e - s).
        THIS IS THE LOAD-BEARING TRIM-CORRECTNESS INVARIANT -- a wrong
        seek/trim recovers the wrong span, which surfaces here as a
        frame-count mismatch, not as a silent success.

    (b) Non-tautological keyframe alignment (opencode H2): builds an
        INDEPENDENT ground-truth keyframe set via keyframe_table_ffprobe
        (the slow, full-scan path -- NOT keyframe_table, which may take the
        fast EBML path the pipeline itself might also take), then for each
        scene exercises the pipeline's OWN pure compute_chunk_seek_trim
        decision and independently re-derives its chosen seek keyframe via
        kf_before, asserting that keyframe is a REAL member of the
        independent ground-truth set. This replaces the old tautological
        `max({f<=s}) exists` check, which could never fail (frame 0 is
        always a keyframe per keyframe_table_ffprobe's own invariant)."""
    scenes = read_scenes(scenes_path)

    total_expect = 0
    for i, (s, e) in enumerate(scenes):
        chunk = workdir / f"chunk_{i:05d}.obu"
        assert chunk.is_file(), (
            f"missing chunk {chunk} -- did the encode invocation include --keep?"
        )
        expect = e - s
        got = count_frames(chunk)
        assert got == expect, (
            f"chunk {i} ({chunk}): got {got} frames, expected {expect} "
            f"(scene [{s},{e})) -- wrong seek/trim recovered the wrong span"
        )
        total_expect += expect

    final_frames = count_frames(final_mkv)
    assert final_frames == total_expect, (
        f"{final_mkv}: {final_frames} frames total, expected {total_expect} "
        f"(sum of independently re-parsed scene spans)"
    )

    fps = probe_fps(src)
    # INDEPENDENT ground truth: full ffprobe packet scan.
    gt_table = keyframe_table_ffprobe(src, fps)
    gt_kf_frames = {f for f, _ in gt_table}
    # PRODUCTION path: what a real `enpipe encode` actually uses to place chunk
    # seeks -- the hand-rolled EBML/Cues fast-path for .mkv (ffprobe fallback
    # otherwise), i.e. the function ARCHITECTURE.md flags as risking a silent
    # "wrong-but-parseable" keyframe table.
    prod_table = keyframe_table(src, fps)
    prod_kf_frames = {f for f, _ in prod_table}

    # Cross-validate the PRODUCTION keyframe path against the INDEPENDENT ground
    # truth. This is the non-tautological check: a corrupt/wrong Cues parse would
    # yield keyframe frames the ffprobe ground truth does not contain, and fail.
    assert prod_kf_frames == gt_kf_frames, (
        f"production keyframe_table (EBML fast-path) disagrees with the "
        f"independent ffprobe ground truth on {src.name}: "
        f"prod-only={sorted(prod_kf_frames - gt_kf_frames)}, "
        f"gt-only={sorted(gt_kf_frames - prod_kf_frames)}"
    )

    for i, (s, e) in enumerate(scenes):
        # Derive the seek from the PRODUCTION table (what real encode used), then
        # assert the chosen keyframe is a genuine keyframe per the INDEPENDENT
        # ground truth -- catches the production path landing a chunk seek on a
        # non-keyframe (silent frame-shift), not just re-checking a table vs itself.
        seek, _trim = compute_chunk_seek_trim(prod_table, s, e)
        kf_frame, kf_time = kf_before(prod_table, s)
        assert kf_frame in gt_kf_frames, (
            f"scene {i}'s production-derived seek keyframe (frame {kf_frame}) is "
            f"NOT in the independent ground-truth keyframe set -- keyframe "
            f"alignment violated (possible wrong-but-parseable Cues table)"
        )
        assert seek == fmt_seek(kf_time)


@pytest.mark.parametrize("metrics", [False, True], ids=["no-metrics", "metrics"])
def test_sdr(tmp_path: Path, request: pytest.FixtureRequest, metrics: bool) -> None:
    src = tmp_path / "sdr.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )
    assert detect_hdr(src) == [], "sanity: SDR clip must classify with no HDR flags"

    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "sdr.av1.mkv"
    workdir = tmp_path / "sdr.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    argv = [
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--jobs", "2",
    ]
    if metrics:
        log_dir = request.getfixturevalue("metrics_tap")
        n = _run_cli_metrics_retry(argv, [workdir, out], log_dir)
        print(f"metrics attempts={n}")
    else:
        _run_cli(argv + ["--no-metrics"])
    assert out.is_file(), f"enpipe encode did not write {out}"
    if metrics:
        _assert_metrics_csv(out)

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)
    _verify_chunk_first_frames(src, workdir, read_scenes(scenes), tmp_path / "content")


_HDR10_CODEC_ARGS: List[str] = [
    "-pix_fmt", "yuv420p10le",
    "-color_primaries", "bt2020", "-color_trc", "smpte2084", "-colorspace", "bt2020nc",
    "-c:v", "libx265", "-preset", "ultrafast",
    # x265 defaults to open-gop=1; enpipe refuses open-GOP sources (qsvencc
    # trim-offset bug) and test_hdr10 is about the HDR10 path, so its source
    # must be closed GOP.
    "-x265-params",
    "hdr10=1:hdr10-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:"
    "colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)"
    "WP(15635,16450)L(10000000,1):max-cll=1000,400:open-gop=0",
]


def _encoder_available(name: str) -> bool:
    """Word-boundary check of `ffmpeg -encoders` output (opencode M4) --
    symmetric with the hardware-availability gate: the self-hosted Arc
    runner's ffmpeg build may lack libx265, so test_hdr10 must skip cleanly
    rather than fail loud on an environment gap."""
    proc = subprocess.run(["ffmpeg", "-hide_banner", "-encoders"],
                           capture_output=True, text=True)
    return re.search(rf"\b{re.escape(name)}\b", proc.stdout) is not None


def _frame_side_data_types(path: Path) -> List[List[str]]:
    """Per-frame list of side_data_type strings, via read-only ffprobe
    (frame=side_data_list) -- shared by the HDR10 survival check here and
    the DV metadata survival check in the DV tests."""
    cmd = [VERIFY_FFPROBE, "-v", "error", "-select_streams", "v:0", "-show_frames",
           "-show_entries", "frame=side_data_list", "-of", "json", str(path)]
    data = json.loads(subprocess.run(cmd, capture_output=True, text=True, check=True).stdout)
    return [
        [sd.get("side_data_type", "") for sd in f.get("side_data_list", [])]
        for f in data.get("frames", [])
    ]


@pytest.mark.parametrize("metrics", [False, True], ids=["no-metrics", "metrics"])
def test_hdr10(tmp_path: Path, request: pytest.FixtureRequest, metrics: bool) -> None:
    if not _encoder_available("libx265"):
        pytest.skip("libx265 encoder not available in this ffmpeg build")

    src = tmp_path / "hdr10.mkv"
    _make_multiscene_clip(src, codec_args=_HDR10_CODEC_ARGS, seg_dur=10)

    assert "--master-display" in detect_hdr(src), (
        "sanity: HDR10 clip must classify with --master-display"
    )

    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "hdr10.av1.mkv"
    workdir = tmp_path / "hdr10.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    argv = [
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
        "--keep", "--no-audio", "--jobs", "2",
    ]
    if metrics:
        log_dir = request.getfixturevalue("metrics_tap")
        n = _run_cli_metrics_retry(argv, [workdir, out], log_dir)
        print(f"metrics attempts={n}")
    else:
        _run_cli(argv + ["--no-metrics"])
    assert out.is_file(), f"enpipe encode did not write {out}"
    if metrics:
        _assert_metrics_csv(out)

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)
    _verify_chunk_first_frames(src, workdir, read_scenes(scenes), tmp_path / "content")

    # HDR10 metadata survival -- FRAME-level (see module docstring's
    # "EMPIRICAL CORRECTION" note): every video frame of the final .mkv
    # must still carry both Mastering-display and Content-light-level side
    # data. Per-frame side data is used here for HDR10 survival ONLY
    # because that is where this pipeline's mkvmerge output actually puts
    # it -- DV RPU (Task 2) also uses frame-level side data, but for a
    # different side_data_type string ("Dolby Vision RPU Data").
    per_frame_types = _frame_side_data_types(out)
    assert per_frame_types, f"no frames read from {out}"
    missing_mastering = sum(
        1 for types in per_frame_types if "Mastering display metadata" not in types
    )
    missing_cll = sum(
        1 for types in per_frame_types if "Content light level metadata" not in types
    )
    assert missing_mastering == 0, (
        f"{missing_mastering}/{len(per_frame_types)} frames of {out} are missing "
        f"Mastering display metadata -- HDR10 survival violated"
    )
    assert missing_cll == 0, (
        f"{missing_cll}/{len(per_frame_types)} frames of {out} are missing "
        f"Content light level metadata -- HDR10 survival violated"
    )


@pytest.mark.parametrize("metrics", [False, True], ids=["no-metrics", "metrics"])
def test_sdr_legacy_oracle_parity(
    tmp_path: Path, request: pytest.FixtureRequest, metrics: bool
) -> None:
    """SC4: legacy/encode_scenes.py remains the executable parity oracle.
    Runs the FROZEN legacy oracle (read-only subprocess, never imported,
    never modified) on the SAME sample + SAME .scenes file the enpipe
    pipeline used, isolating ENCODE parity from detect. With metrics=True
    both sides run with --psnr/--ssim (retry rule: see module docstring);
    with metrics=False both pass --no-metrics."""
    src = tmp_path / "sdr_parity.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )
    scenes = src.with_name(src.name + ".scenes")

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    wd_enpipe = tmp_path / "wd_enpipe"
    enpipe_out = tmp_path / "enpipe_out.mkv"
    en_argv = [
        "encode", str(src), str(scenes),
        "-o", str(enpipe_out), "--workdir", str(wd_enpipe),
        "--keep", "--no-audio", "--jobs", "2",
    ]
    if metrics:
        log_dir = request.getfixturevalue("metrics_tap")
        n_en = _run_cli_metrics_retry(en_argv, [wd_enpipe, enpipe_out], log_dir)
        print(f"metrics attempts enpipe={n_en}")
    else:
        _run_cli(en_argv + ["--no-metrics"])
    assert enpipe_out.is_file()

    wd_legacy = tmp_path / "wd_legacy"
    legacy_out = tmp_path / "legacy_out.mkv"
    legacy_cmd = [
        sys.executable, str(REPO_ROOT / "legacy" / "encode_scenes.py"),
        str(src), str(scenes),
        "-o", str(legacy_out), "--workdir", str(wd_legacy),
        "--keep", "--no-audio", "--jobs", "2",
    ]
    if metrics:
        legacy_proc, n_lg = _run_legacy_metrics_retry(
            legacy_cmd, [wd_legacy, legacy_out], log_dir
        )
        print(f"metrics attempts legacy={n_lg}")
    else:
        legacy_cmd.append("--no-metrics")
        legacy_proc = subprocess.run(
            legacy_cmd, cwd=REPO_ROOT, capture_output=True, text=True
        )
    assert legacy_proc.returncode == 0, (
        f"legacy oracle encode_scenes.py failed (rc={legacy_proc.returncode}): "
        f"{legacy_proc.stderr[-2000:]}"
    )
    assert legacy_out.is_file()
    if metrics:
        _assert_metrics_csv(enpipe_out)
        _assert_metrics_csv(legacy_out)

    scenes_list = read_scenes(scenes)
    _verify_chunk_first_frames(src, wd_enpipe, scenes_list, tmp_path / "content_en")
    _verify_chunk_first_frames(src, wd_legacy, scenes_list, tmp_path / "content_lg")

    # PRIMARY GATE: final .mkv frame-count parity.
    assert count_frames(legacy_out) == count_frames(enpipe_out), (
        "enpipe encode frame count does not match the frozen legacy oracle "
        "on the same sample + scenes"
    )

    # Determinism-aware PRE-MUX movie.obu comparison (scratch/parity_encode.py:199-234):
    # byte-identical -> qsvencc is deterministic on this box (STRONG gate holds).
    # differ -> HW AV1 is commonly non-deterministic (EXPECTED case per
    # parity_encode.py) -> fall back to frame-count parity on the pre-mux .obu,
    # which is correct, not a weakening of the check.
    legacy_movie = wd_legacy / "movie.obu"
    enpipe_movie = wd_enpipe / "movie.obu"
    assert legacy_movie.is_file() and enpipe_movie.is_file()
    if legacy_movie.read_bytes() == enpipe_movie.read_bytes():
        pass  # deterministic qsvencc on this box -- byte-identical parity holds
    else:
        assert count_frames(legacy_movie) == count_frames(enpipe_movie), (
            "pre-mux movie.obu differs AND frame counts differ -- qsvencc "
            "non-determinism alone cannot explain this; real parity failure"
        )


# --------------------------------------------------------------------------- #
# D-06/D-07: fixture-gated HDR10+/Dolby-Vision cases. Genuine HDR10+ dynamic
# metadata and genuine DV RPU content cannot be reliably synthesized
# in-sandbox (04-RESEARCH.md "What is confirmed NOT synthesizable") -- these
# tests look for operator-supplied real sample files at FIXTURES_DIR and
# skip cleanly with an explanatory how-to-supply message when absent. A
# pass is NEVER faked: absence of a fixture is not treated as success.
# --------------------------------------------------------------------------- #

FIXTURES_DIR = Path(
    os.environ.get("ENPIPE_TEST_MEDIA", str(REPO_ROOT / "tests" / "fixtures" / "media"))
)


def _fixture(name: str) -> Optional[Path]:
    p = FIXTURES_DIR / name
    return p if p.is_file() else None


def _verify_ffmpeg() -> str:
    """ffmpeg sibling of VERIFY_FFPROBE (same build), else ffmpeg from PATH."""
    probe = Path(VERIFY_FFPROBE)
    if probe.parent != Path("."):
        suffix = probe.name[len("ffprobe"):] if probe.name.startswith("ffprobe") else ""
        return str(probe.parent / ("ffmpeg" + suffix))
    return "ffmpeg"


def _source_start_time(src: Path) -> float:
    """Container start_time of the source (read-only probe)."""
    out = subprocess.run(
        [VERIFY_FFPROBE, "-v", "error", "-show_entries", "format=start_time",
         "-of", "default=nw=1:nk=1", str(src)],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    try:
        return float(out)
    except ValueError:
        return 0.0


def _verify_chunk_first_frames(
    src: Path, workdir: Path, scenes: List[Tuple[int, int]], tmp: Path
) -> int:
    """First frame of chunk_{i:05d}.obu vs source frame S (scene start), by
    PSNR, with a wrong-GOP negative control at S+(K_next-K). Chunks are
    numbered from 0 within `scenes`. Returns the number of chunks where the
    negative control was discriminating. Collect-then-report."""
    ffmpeg = _verify_ffmpeg()
    fps = probe_fps(src)
    table = keyframe_table_ffprobe(src, fps)  # independent ground truth
    total = count_frames(src)
    start_time = _source_start_time(src)
    kf_frames = [f for f, _ in table]
    tmp.mkdir(parents=True, exist_ok=True)

    errors: List[str] = []
    oks: List[float] = []
    disc_count = 0
    for i, (s, e) in enumerate(scenes):
        chunk = workdir / f"chunk_{i:05d}.obu"
        k, k_time = kf_before(table, s)
        later = [f for f in kf_frames if f > k]
        k_next = later[0] if later else None
        alt = s + (k_next - k) if k_next is not None else None
        if alt is not None and alt >= total:
            alt = None

        c0 = tmp / f"c{i:05d}_chunk.mkv"
        content.extract_chunk_first_frame(ffmpeg, chunk, c0)
        ref = tmp / f"c{i:05d}_src_s.mkv"
        content.extract_source_frame(ffmpeg, src, s, k, k_time, fps, start_time, ref)
        psnr_ok = content.psnr_db(ffmpeg, c0, ref)
        psnr_alt: Optional[float] = None
        psnr_src_alt: Optional[float] = None
        if alt is not None:
            # K of the alt frame, for the fast extraction path
            ka, ka_time = kf_before(table, alt)
            ref_alt = tmp / f"c{i:05d}_src_alt.mkv"
            content.extract_source_frame(
                ffmpeg, src, alt, ka, ka_time, fps, start_time, ref_alt
            )
            psnr_alt = content.psnr_db(ffmpeg, c0, ref_alt)
            psnr_src_alt = content.psnr_db(ffmpeg, ref, ref_alt)
        err, disc = content.first_frame_verdict(psnr_ok, psnr_alt, psnr_src_alt)
        oks.append(psnr_ok)
        disc_count += 1 if disc else 0
        print(
            f"[content] {src.name} chunk {i} scene [{s},{e}) K={k} K_next={k_next} "
            f"psnr_ok={psnr_ok:.2f} psnr_alt={psnr_alt} psnr_src_alt={psnr_src_alt} "
            f"discriminating={disc}"
        )
        if err is not None:
            errors.append(
                f"chunk {i} scene [{s},{e}) K={k} K_next={k_next}: {err} "
                f"(psnr_ok={psnr_ok:.2f}, psnr_alt={psnr_alt}, "
                f"psnr_src_alt={psnr_src_alt})"
            )
    print(
        f"[content] {src.name}: min psnr_ok={min(oks) if oks else None}, "
        f"discriminating chunks={disc_count}/{len(scenes)}"
    )
    assert not errors, (
        f"chunk content mismatch on {src.name} (frame counts may still match -- "
        f"suspect a qsvencc seek issue; the firstpkt seek bug is "
        f"fixed in r4663, see .planning/debug/HANDOFF-qsvencc-seek-firstpkt.md):\n" + "\n".join(errors)
    )
    return disc_count


def _av1_dovi_self_check() -> bool:
    """Read-only AV1-DOVI-parsing self-check (D-07/Assumption A2, opencode
    L2): confirms that the ffmpeg build matching the verification ffprobe
    (see _verify_ffmpeg) has a dovi_rpu bitstream filter declaring AV1
    support in its Supported-codecs line via a WORD-BOUNDARY match (not
    a bare substring, which could match spuriously). This is a READ-ONLY
    `-h` (help) invocation -- it does not filter, mutate, or process any
    media; it only inspects what that ffmpeg build claims to support, so a
    toolchain downgrade fails loud (skip with an explanation) rather than
    silently under-reporting DV frames. A missing binary counts as
    unsupported."""
    try:
        proc = subprocess.run([_verify_ffmpeg(), "-hide_banner", "-h", "bsf=dovi_rpu"],
                              capture_output=True, text=True)
    except (FileNotFoundError, PermissionError):
        return False
    return re.search(r"\bav1\b", proc.stdout + proc.stderr, re.I) is not None


def _dv_metadata_frame_count(path: Path) -> Tuple[int, int]:
    """Returns (frames_with_dv_metadata, total_frames) via the SAME read-only
    frame-level ffprobe probe as the HDR10 survival check
    (_frame_side_data_types) -- no bitstream filter, no mutation.

    Counts frames whose side_data_list contains "Dolby Vision Metadata".
    ffprobe's default AV1 decoder (libdav1d) exports the parsed RPU under
    that name, whereas the raw "Dolby Vision RPU Data" entry only exists on
    the HEVC source -- counting RPU Data would yield 0 on the AV1 output even
    when every RPU survived. "Dolby Vision Metadata" is present on both, so
    source-vs-output parity compares like with like; it also works on a raw
    .obu chunk. The native av1 decoder exports no DV side data at all, hence
    the reliance on ffprobe's default decoder (libdav1d)."""
    per_frame_types = _frame_side_data_types(path)
    with_md = sum(1 for types in per_frame_types if "Dolby Vision Metadata" in types)
    return with_md, len(per_frame_types)


def _dovi_config_record(path: Path) -> Optional[Dict[str, Any]]:
    """First "DOVI configuration record" side-data entry of the first video
    stream, or None. Full -show_streams is required:
    `-show_entries stream=side_data_list` returns empty dicts."""
    cmd = [VERIFY_FFPROBE, "-v", "error", "-select_streams", "v:0",
           "-show_streams", "-of", "json", str(path)]
    data = json.loads(subprocess.run(cmd, capture_output=True, text=True, check=True).stdout)
    streams = data.get("streams", [])
    if not streams:
        return None
    for sd in streams[0].get("side_data_list", []):
        if sd.get("side_data_type") == "DOVI configuration record":
            return sd
    return None


def test_hdr10plus(tmp_path: Path) -> None:
    fixture = _fixture("hdr10plus.mkv")
    if fixture is None:
        pytest.skip(
            f"no HDR10+ fixture at {FIXTURES_DIR / 'hdr10plus.mkv'} (or set "
            f"$ENPIPE_TEST_MEDIA to a directory containing hdr10plus.mkv) -- "
            f"see tests/fixtures/media/README.md for how to supply one. This "
            f"is NOT a failure: genuine HDR10+ dynamic-metadata source "
            f"material cannot be synthesized (D-06) and must be operator-"
            f"supplied."
        )

    src = tmp_path / fixture.name
    shutil.copyfile(fixture, src)
    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / "hdr10plus.av1.mkv"
    workdir = tmp_path / "hdr10plus.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
    # metrics path covered by parametrized tests above (D-10d scope decision, Phase 8)
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)
    _verify_chunk_first_frames(src, workdir, read_scenes(scenes), tmp_path / "content")


def test_run_parity_vs_two_step(tmp_path: Path) -> None:
    """Phase 5 (D-08): `enpipe run` vs the manual two-step (`enpipe detect`
    then `enpipe encode`) on real Arc hardware. Byte-identical parity is
    guaranteed by construction (D-02) -- run_pipeline builds the same
    per-stage Namespaces the manual two-step CLI produces and writes the
    intermediate `.scenes` to the same derived path (D-04) -- this test
    proves it. Mirrors the determinism-aware pre-mux movie.obu pattern of
    test_sdr_legacy_oracle_parity above, but compares run-vs-two-step
    instead of enpipe-vs-legacy-oracle."""
    src = tmp_path / "run_parity.mkv"
    _make_multiscene_clip(
        src,
        codec_args=["-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p"],
        seg_dur=10,
    )

    # --- SINGLE-COMMAND side: `enpipe run` --- #
    run_out = tmp_path / "run_out.mkv"
    wd_run = tmp_path / "wd_run"
    _run_cli([
        "run", str(src), "-o", str(run_out),
    # metrics path covered by parametrized tests above (D-10d scope decision, Phase 8)
        "--workdir", str(wd_run), "--keep", "--no-audio", "--no-metrics",
        "--detect-jobs", "2", "--encode-jobs", "2",
    ])
    assert run_out.is_file(), f"enpipe run did not write {run_out}"
    # same derivation run_detect itself uses (detection/pipeline.py:42)
    run_scenes = Path(str(src) + ".scenes")
    assert run_scenes.is_file(), (
        f"enpipe run did not keep the .scenes intermediate at {run_scenes} (D-04)"
    )

    # --- TWO-STEP side: manual `enpipe detect` + `enpipe encode`, on a
    # fresh copy of src so its derived `.scenes` path does not collide with
    # run_scenes above --- #
    two_step_dir = tmp_path / "two_step"
    two_step_dir.mkdir()
    src2 = two_step_dir / src.name
    shutil.copyfile(src, src2)
    scenes2 = Path(str(src2) + ".scenes")

    two_out = tmp_path / "two_out.mkv"
    wd_two = tmp_path / "wd_two"
    _run_cli(["detect", str(src2), "--jobs", "2"])
    assert scenes2.is_file(), f"enpipe detect did not write {scenes2}"
    _run_cli([
        "encode", str(src2), str(scenes2),
        "-o", str(two_out), "--workdir", str(wd_two),
    # metrics path covered by parametrized tests above (D-10d scope decision, Phase 8)
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert two_out.is_file(), f"enpipe encode did not write {two_out}"

    # COLLISION-AVOIDANCE: distinct tmp copies -> distinct derived paths.
    assert run_scenes != scenes2

    run_scene_list = read_scenes(run_scenes)
    _verify_chunk_first_frames(src, wd_run, run_scene_list, tmp_path / "content_run")
    _verify_chunk_first_frames(src2, wd_two, run_scene_list, tmp_path / "content_two")

    # PRIMARY GATE: final .mkv frame-count parity.
    assert count_frames(run_out) == count_frames(two_out), (
        "enpipe run frame count does not match the manual two-step on the "
        "same source"
    )

    # Determinism-aware PRE-MUX movie.obu comparison (mirrors
    # test_sdr_legacy_oracle_parity above): byte-identical -> qsvencc
    # deterministic on this box (STRONG gate holds); differ -> fall back to
    # frame-count parity on the pre-mux .obu (expected HW AV1
    # non-determinism, not a weakening).
    run_movie = wd_run / "movie.obu"
    two_movie = wd_two / "movie.obu"
    assert run_movie.is_file() and two_movie.is_file()
    if run_movie.read_bytes() == two_movie.read_bytes():
        pass  # deterministic qsvencc on this box -- byte-identical parity holds
    else:
        assert count_frames(run_movie) == count_frames(two_movie), (
            "pre-mux movie.obu differs AND frame counts differ -- qsvencc "
            "non-determinism alone cannot explain this; real parity failure"
        )

    # SCENES BYTE-IDENTITY: detect stage is identical by construction
    # (PySceneDetect is deterministic on a fixed input) even though the
    # run-side and two-step-side .scenes live at different paths.
    assert run_scenes.read_bytes() == scenes2.read_bytes(), (
        "run-side .scenes differs from the two-step-side .scenes byte-for-byte"
    )


def _run_dv_case(
    tmp_path: Path,
    fixture: Path,
    stem: str,
    expected_out_compat: Optional[int] = None,
) -> None:
    if not _av1_dovi_self_check():
        pytest.skip(
            "the ffmpeg matching the verification ffprobe has a dovi_rpu "
            "bitstream filter without AV1 support -- cannot verify AV1 DV "
            "side-data (see 04-RESEARCH.md 'DV RPU Verification Mechanism' "
            "/ Assumption A2); point ENPIPE_TEST_FFPROBE at an ffprobe from "
            "ffmpeg >= 7 (e.g. a BtbN static build)"
        )

    src_cfg = _dovi_config_record(fixture)
    assert src_cfg is not None, f"{fixture} has no DOVI configuration record -- not a DV fixture"
    src_compat = src_cfg["dv_bl_signal_compatibility_id"]

    src_with_md, src_total = _dv_metadata_frame_count(fixture)
    assert src_with_md > 0, (
        f"DV fixture {fixture} carries no per-frame Dolby Vision metadata -- "
        f"not a valid DV fixture, or the fixture itself lacks genuine RPU"
    )

    src = tmp_path / fixture.name
    shutil.copyfile(fixture, src)
    scenes = src.with_name(src.name + ".scenes")
    out = tmp_path / f"{stem}.av1.mkv"
    workdir = tmp_path / f"{stem}.chunks"

    _run_cli(["detect", str(src), "--jobs", "2"])
    assert scenes.is_file(), f"enpipe detect did not write {scenes}"

    _run_cli([
        "encode", str(src), str(scenes),
        "-o", str(out), "--workdir", str(workdir),
    # metrics path covered by parametrized tests above (D-10d scope decision, Phase 8)
        "--keep", "--no-audio", "--no-metrics", "--jobs", "2",
    ])
    assert out.is_file(), f"enpipe encode did not write {out}"

    _verify_frame_counts_and_keyframes(src, workdir, scenes, out)
    _verify_chunk_first_frames(src, workdir, read_scenes(scenes), tmp_path / "content")

    # SOURCE-parity of the DV metadata frame count (opencode M1/qwen M3): the
    # genuine survival invariant is that the count SURVIVES the splice/mux,
    # matching the SOURCE fixture's own count -- not merely "== total", which
    # would be too strict if the source itself is partial (e.g. RPU present
    # only on some frames).
    out_with_md, out_total = _dv_metadata_frame_count(out)
    assert out_with_md == src_with_md and out_with_md > 0, (
        f"DV metadata frame-count did not survive splice/mux: source had "
        f"{src_with_md}/{src_total} frames with DV metadata, final output "
        f"has {out_with_md}/{out_total}"
    )

    # ALSO check source-parity at the pre-mux .obu chunk level (RESEARCH
    # Assumption A3 -- mkvmerge's DV-side-data mux path is distinct from
    # HDR10's, so pre-mux and post-mux must both be verified independently).
    scene_list = read_scenes(scenes)
    chunk_with_md_total = 0
    for i in range(len(scene_list)):
        chunk = workdir / f"chunk_{i:05d}.obu"
        w, _ = _dv_metadata_frame_count(chunk)
        chunk_with_md_total += w
    assert chunk_with_md_total == src_with_md, (
        f"pre-mux chunk DV metadata frame total ({chunk_with_md_total}) does "
        f"not match source count ({src_with_md})"
    )

    # Output configuration record: AV1 Dolby Vision is always profile 10.
    # mkvmerge derives the record from the stream itself, not from qsvencc's
    # --dolby-vision-profile flag.
    out_cfg = _dovi_config_record(out)
    assert out_cfg is not None, (
        f"output {out} has no DOVI configuration record (source: {src_cfg})"
    )
    assert out_cfg["dv_profile"] == 10, (
        f"output DV profile is not 10: source record {src_cfg}, output record {out_cfg}"
    )
    expected = src_compat if expected_out_compat is None else expected_out_compat
    if expected_out_compat is not None:
        # Sanity: the fixture really is the profile this test implies.
        assert src_compat == expected_out_compat, (
            f"fixture {fixture} has bl_signal_compatibility_id {src_compat}, "
            f"test expects {expected_out_compat}: source record {src_cfg}"
        )
    assert out_cfg["dv_bl_signal_compatibility_id"] == expected, (
        f"output bl_signal_compatibility_id != {expected}: "
        f"source record {src_cfg}, output record {out_cfg}"
    )


def test_dv(tmp_path: Path) -> None:
    fixture = _fixture("dv.mkv")
    if fixture is None:
        pytest.skip(
            f"no Dolby Vision fixture at {FIXTURES_DIR / 'dv.mkv'} (or set "
            f"$ENPIPE_TEST_MEDIA to a directory containing dv.mkv) -- see "
            f"tests/fixtures/media/README.md for how to supply one. This is "
            f"NOT a failure: genuine DV RPU source material cannot be "
            f"synthesized (D-06) and must be operator-supplied."
        )
    _run_dv_case(tmp_path, fixture, "dv")


def _make_open_gop_source(dst: Path, *, open_gop: bool) -> None:
    """12 s 1280x720 10-bit HEVC mp4 (software x265): keyframes every 48 frames
    (0,48,96,144,192,240), B-frames on, four visibly different MOVING scenes
    of 70/80/70/68 frames -> cuts at 70, 150 and 220, all mid-GOP (a scene
    starting exactly on a keyframe is avoided here). `open_gop` sets x265's
    open-gop explicitly (never the default): True gives CRA + leading pictures
    (enpipe must refuse it), False a closed-GOP twin with the same layout.
    mp4 rather than TS: a TS start_time of ~0.083 s breaks the pipeline's own
    keyframe table before encoding, while mp4 has start_time 0."""
    rate = "24000/1001"
    size = "1280x720"
    sources = [
        f"testsrc2=size={size}:rate={rate}",
        f"mandelbrot=size={size}:rate={rate}",
        f"gradients=size={size}:rate={rate}:speed=0.05",
        f"life=size={size}:rate={rate}:mold=10:ratio=0.1:"
        f"death_color=#C83232:life_color=#00ff00",
    ]
    lengths = [70, 80, 70, 68]
    inputs: List[str] = []
    fc = ""
    for i, (srcspec, n) in enumerate(zip(sources, lengths)):
        inputs += ["-f", "lavfi", "-i", srcspec]
        fc += (
            f"[{i}:v]trim=end_frame={n},setpts=PTS-STARTPTS,"
            f"format=yuv420p10le[v{i}];"
        )
    fc += "".join(f"[v{i}]" for i in range(len(sources)))
    fc += f"concat=n={len(sources)}:v=1[v]"
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", *inputs,
         "-filter_complex", fc, "-map", "[v]",
         "-c:v", "libx265", "-preset", "ultrafast",
         "-x265-params",
         f"keyint=48:min-keyint=48:scenecut=0:bframes=4:log-level=error:"
         f"open-gop={1 if open_gop else 0}",
         str(dst)],
        check=True, capture_output=True,
    )


def _prepare_mid_gop_source(tmp_path: Path, *, open_gop: bool):
    """Build the synthetic source, run detect, check layout preconditions
    (pytest.fail, not assert). Returns (src, scenes_path, scenes, included)."""
    if not _encoder_available("libx265"):
        pytest.skip("libx265 encoder not available in this ffmpeg build")

    src = tmp_path / "syn.mp4"
    _make_open_gop_source(src, open_gop=open_gop)

    _run_cli(["detect", str(src), "--jobs", "2"])
    scenes_path = src.with_name(src.name + ".scenes")
    scenes = read_scenes(scenes_path)
    if len(scenes) < 3:
        pytest.fail(f"precondition: need >= 3 scenes, got {scenes}")
    included = scenes[:-1]
    fps = probe_fps(src)
    table = keyframe_table_ffprobe(src, fps)
    last_kf = max(f for f, _ in table)
    kfs = {f for f, _ in table}
    if not any(s not in kfs for s, _ in included):
        pytest.fail(f"precondition: no scene starts mid-GOP: {scenes}, kf={sorted(kfs)}")
    if any(e > last_kf for _, e in included):
        pytest.fail(
            f"precondition: included scenes must end <= last keyframe {last_kf}: {scenes}"
        )
    return src, scenes_path, scenes, included, fps, table


def test_open_gop_source_refused(tmp_path: Path) -> None:
    """An open-GOP source (leading pictures after a seek keyframe) must be
    refused by enpipe before any chunk is encoded: qsvencc shifts --trim by -N
    on such sources, which keeps frame counts but silently corrupts content."""
    src, scenes_path, scenes, included, fps, table = _prepare_mid_gop_source(
        tmp_path, open_gop=True)

    used = sorted({kf_before(table, s) for s, _ in scenes[:-1]})
    leading = probe_leading_frames(src, fps, used)
    if not any(n > 0 for n in leading.values()):
        pytest.fail(f"precondition: no leading frames after used keyframes: {leading}")

    out = tmp_path / "syn.av1.mkv"
    workdir = tmp_path / "syn.chunks"
    with pytest.raises(SystemExit) as excinfo:
        _enpipe_main([
            "encode", str(src), str(scenes_path),
            "-o", str(out), "--workdir", str(workdir), "--keep", "--no-audio",
            "--no-metrics", "--jobs", "2", "--from", "0", "--to", str(len(scenes) - 1),
        ])
    assert "open-GOP" in str(excinfo.value)
    assert not list(workdir.glob("chunk_*.obu"))


def test_chunk_content_closed_gop(tmp_path: Path) -> None:
    """Same mid-GOP layout as the open-GOP source but closed GOP: the chunk
    content check must pass (covers the qsvencc r4663 seek fix on mid-GOP
    cuts). Precondition problems and encode failures use pytest.fail()."""
    src, scenes_path, scenes, included, _fps, _table = _prepare_mid_gop_source(
        tmp_path, open_gop=False)

    out = tmp_path / "syn.av1.mkv"
    workdir = tmp_path / "syn.chunks"
    # The last scene is excluded so no included scene overruns the end of the
    # file (K_next + len > last frame) and the content check is reached.
    _run_cli([
        "encode", str(src), str(scenes_path),
        "-o", str(out), "--workdir", str(workdir), "--keep", "--no-audio",
        "--no-metrics", "--jobs", "2", "--from", "0", "--to", str(len(scenes) - 1),
    ])
    total_expect = 0
    for i, (s, e) in enumerate(included):
        got = count_frames(workdir / f"chunk_{i:05d}.obu")
        if got != e - s:
            pytest.fail(f"chunk {i}: {got} frames, expected {e - s}")
        total_expect += e - s
    if count_frames(out) != total_expect:
        pytest.fail(f"{out}: {count_frames(out)} frames, expected {total_expect}")

    disc = _verify_chunk_first_frames(src, workdir, included, tmp_path / "content")
    if disc == 0:
        pytest.fail("negative control never discriminated -- check is vacuous")


def test_dv_profile5(tmp_path: Path) -> None:
    """DV profile 5 (IPTPQc2 base layer, bl_signal_compatibility_id 0) source
    -> AV1 profile 10.0. Guards against the output being flagged as 10.1
    (HDR10-compatible), which a profile 5 base layer is not.

    Relies on the `--seek` fix of qsvencc >= r4663 (8.32-vppsync6): the last
    chunk lands in the source's last GOP."""
    fixture = _fixture("dv-p5.mkv")
    if fixture is None:
        pytest.skip(
            f"no Dolby Vision profile 5 fixture at {FIXTURES_DIR / 'dv-p5.mkv'} "
            f"(or set $ENPIPE_TEST_MEDIA to a directory containing dv-p5.mkv) "
            f"-- a DV profile 5 (bl_signal_compatibility_id 0, IPTPQc2 base "
            f"layer) source; see tests/fixtures/media/README.md. This is NOT "
            f"a failure: genuine DV material cannot be synthesized (D-06) "
            f"and must be operator-supplied."
        )
    src_cfg = _dovi_config_record(fixture)
    assert src_cfg is not None and src_cfg["dv_profile"] == 5, (
        f"{fixture} is not a DV profile 5 source: {src_cfg}"
    )
    _run_dv_case(tmp_path, fixture, "dv-p5", expected_out_compat=0)
